#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicDatabaseBuilder
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MagicDatabase")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCard(Card instance);
    partial void UpdateCard(Card instance);
    partial void DeleteCard(Card instance);
    #endregion
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Card> Cards
		{
			get
			{
				return this.GetTable<Card>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cards")]
	public partial class Card : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Name;
		
		private string _Names;
		
		private string _ManaCost;
		
		private System.Nullable<int> _CMC;
		
		private string _Colors;
		
		private string _Type;
		
		private string _Supertypes;
		
		private string _Types;
		
		private string _Subtypes;
		
		private string _Rarity;
		
		private string _Text;
		
		private string _Flavor;
		
		private string _Artist;
		
		private string _Number;
		
		private string _Power;
		
		private string _Toughness;
		
		private System.Nullable<int> _Loyalty;
		
		private string _Layout;
		
		private System.Nullable<int> _MultiverseID;
		
		private string _Variations;
		
		private string _ImageName;
		
		private string _Watermark;
		
		private string _Border;
		
		private string _Timeshifted;
		
		private System.Nullable<int> _HandSizeModifier;
		
		private System.Nullable<int> _LifeModifier;
		
		private string _Reserved;
		
		private string _ReleaseDate;
		
		private string _Rulings;
		
		private string _ForeignNames;
		
		private string _Printings;
		
		private string _OriginalText;
		
		private string _OriginalType;
		
		private string _Legalities;
		
		private string _Source;
		
		private int _ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNamesChanging(string value);
    partial void OnNamesChanged();
    partial void OnManaCostChanging(string value);
    partial void OnManaCostChanged();
    partial void OnCMCChanging(System.Nullable<int> value);
    partial void OnCMCChanged();
    partial void OnColorsChanging(string value);
    partial void OnColorsChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnSupertypesChanging(string value);
    partial void OnSupertypesChanged();
    partial void OnTypesChanging(string value);
    partial void OnTypesChanged();
    partial void OnSubtypesChanging(string value);
    partial void OnSubtypesChanged();
    partial void OnRarityChanging(string value);
    partial void OnRarityChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnFlavorChanging(string value);
    partial void OnFlavorChanged();
    partial void OnArtistChanging(string value);
    partial void OnArtistChanged();
    partial void OnNumberChanging(string value);
    partial void OnNumberChanged();
    partial void OnPowerChanging(string value);
    partial void OnPowerChanged();
    partial void OnToughnessChanging(string value);
    partial void OnToughnessChanged();
    partial void OnLoyaltyChanging(System.Nullable<int> value);
    partial void OnLoyaltyChanged();
    partial void OnLayoutChanging(string value);
    partial void OnLayoutChanged();
    partial void OnMultiverseIDChanging(System.Nullable<int> value);
    partial void OnMultiverseIDChanged();
    partial void OnVariationsChanging(string value);
    partial void OnVariationsChanged();
    partial void OnImageNameChanging(string value);
    partial void OnImageNameChanged();
    partial void OnWatermarkChanging(string value);
    partial void OnWatermarkChanged();
    partial void OnBorderChanging(string value);
    partial void OnBorderChanged();
    partial void OnTimeshiftedChanging(string value);
    partial void OnTimeshiftedChanged();
    partial void OnHandSizeModifierChanging(System.Nullable<int> value);
    partial void OnHandSizeModifierChanged();
    partial void OnLifeModifierChanging(System.Nullable<int> value);
    partial void OnLifeModifierChanged();
    partial void OnReservedChanging(string value);
    partial void OnReservedChanged();
    partial void OnReleaseDateChanging(string value);
    partial void OnReleaseDateChanged();
    partial void OnRulingsChanging(string value);
    partial void OnRulingsChanged();
    partial void OnForeignNamesChanging(string value);
    partial void OnForeignNamesChanged();
    partial void OnPrintingsChanging(string value);
    partial void OnPrintingsChanged();
    partial void OnOriginalTextChanging(string value);
    partial void OnOriginalTextChanged();
    partial void OnOriginalTypeChanging(string value);
    partial void OnOriginalTypeChanged();
    partial void OnLegalitiesChanging(string value);
    partial void OnLegalitiesChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    #endregion
		
		public Card()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Names", DbType="NVarChar(MAX)")]
		public string Names
		{
			get
			{
				return this._Names;
			}
			set
			{
				if ((this._Names != value))
				{
					this.OnNamesChanging(value);
					this.SendPropertyChanging();
					this._Names = value;
					this.SendPropertyChanged("Names");
					this.OnNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManaCost", DbType="NVarChar(MAX)")]
		public string ManaCost
		{
			get
			{
				return this._ManaCost;
			}
			set
			{
				if ((this._ManaCost != value))
				{
					this.OnManaCostChanging(value);
					this.SendPropertyChanging();
					this._ManaCost = value;
					this.SendPropertyChanged("ManaCost");
					this.OnManaCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMC", DbType="Int")]
		public System.Nullable<int> CMC
		{
			get
			{
				return this._CMC;
			}
			set
			{
				if ((this._CMC != value))
				{
					this.OnCMCChanging(value);
					this.SendPropertyChanging();
					this._CMC = value;
					this.SendPropertyChanged("CMC");
					this.OnCMCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colors", DbType="NVarChar(MAX)")]
		public string Colors
		{
			get
			{
				return this._Colors;
			}
			set
			{
				if ((this._Colors != value))
				{
					this.OnColorsChanging(value);
					this.SendPropertyChanging();
					this._Colors = value;
					this.SendPropertyChanged("Colors");
					this.OnColorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(MAX)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supertypes", DbType="NVarChar(MAX)")]
		public string Supertypes
		{
			get
			{
				return this._Supertypes;
			}
			set
			{
				if ((this._Supertypes != value))
				{
					this.OnSupertypesChanging(value);
					this.SendPropertyChanging();
					this._Supertypes = value;
					this.SendPropertyChanged("Supertypes");
					this.OnSupertypesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Types", DbType="NVarChar(MAX)")]
		public string Types
		{
			get
			{
				return this._Types;
			}
			set
			{
				if ((this._Types != value))
				{
					this.OnTypesChanging(value);
					this.SendPropertyChanging();
					this._Types = value;
					this.SendPropertyChanged("Types");
					this.OnTypesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtypes", DbType="NVarChar(MAX)")]
		public string Subtypes
		{
			get
			{
				return this._Subtypes;
			}
			set
			{
				if ((this._Subtypes != value))
				{
					this.OnSubtypesChanging(value);
					this.SendPropertyChanging();
					this._Subtypes = value;
					this.SendPropertyChanged("Subtypes");
					this.OnSubtypesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rarity", DbType="NVarChar(MAX)")]
		public string Rarity
		{
			get
			{
				return this._Rarity;
			}
			set
			{
				if ((this._Rarity != value))
				{
					this.OnRarityChanging(value);
					this.SendPropertyChanging();
					this._Rarity = value;
					this.SendPropertyChanged("Rarity");
					this.OnRarityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NVarChar(MAX)")]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this.OnTextChanging(value);
					this.SendPropertyChanging();
					this._Text = value;
					this.SendPropertyChanged("Text");
					this.OnTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flavor", DbType="NVarChar(MAX)")]
		public string Flavor
		{
			get
			{
				return this._Flavor;
			}
			set
			{
				if ((this._Flavor != value))
				{
					this.OnFlavorChanging(value);
					this.SendPropertyChanging();
					this._Flavor = value;
					this.SendPropertyChanged("Flavor");
					this.OnFlavorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Artist", DbType="NVarChar(MAX)")]
		public string Artist
		{
			get
			{
				return this._Artist;
			}
			set
			{
				if ((this._Artist != value))
				{
					this.OnArtistChanging(value);
					this.SendPropertyChanging();
					this._Artist = value;
					this.SendPropertyChanged("Artist");
					this.OnArtistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="NVarChar(MAX)")]
		public string Number
		{
			get
			{
				return this._Number;
			}
			set
			{
				if ((this._Number != value))
				{
					this.OnNumberChanging(value);
					this.SendPropertyChanging();
					this._Number = value;
					this.SendPropertyChanged("Number");
					this.OnNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Power", DbType="NVarChar(MAX)")]
		public string Power
		{
			get
			{
				return this._Power;
			}
			set
			{
				if ((this._Power != value))
				{
					this.OnPowerChanging(value);
					this.SendPropertyChanging();
					this._Power = value;
					this.SendPropertyChanged("Power");
					this.OnPowerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Toughness", DbType="NVarChar(MAX)")]
		public string Toughness
		{
			get
			{
				return this._Toughness;
			}
			set
			{
				if ((this._Toughness != value))
				{
					this.OnToughnessChanging(value);
					this.SendPropertyChanging();
					this._Toughness = value;
					this.SendPropertyChanged("Toughness");
					this.OnToughnessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loyalty", DbType="Int")]
		public System.Nullable<int> Loyalty
		{
			get
			{
				return this._Loyalty;
			}
			set
			{
				if ((this._Loyalty != value))
				{
					this.OnLoyaltyChanging(value);
					this.SendPropertyChanging();
					this._Loyalty = value;
					this.SendPropertyChanged("Loyalty");
					this.OnLoyaltyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Layout", DbType="NVarChar(MAX)")]
		public string Layout
		{
			get
			{
				return this._Layout;
			}
			set
			{
				if ((this._Layout != value))
				{
					this.OnLayoutChanging(value);
					this.SendPropertyChanging();
					this._Layout = value;
					this.SendPropertyChanged("Layout");
					this.OnLayoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MultiverseID", DbType="Int")]
		public System.Nullable<int> MultiverseID
		{
			get
			{
				return this._MultiverseID;
			}
			set
			{
				if ((this._MultiverseID != value))
				{
					this.OnMultiverseIDChanging(value);
					this.SendPropertyChanging();
					this._MultiverseID = value;
					this.SendPropertyChanged("MultiverseID");
					this.OnMultiverseIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Variations", DbType="NVarChar(MAX)")]
		public string Variations
		{
			get
			{
				return this._Variations;
			}
			set
			{
				if ((this._Variations != value))
				{
					this.OnVariationsChanging(value);
					this.SendPropertyChanging();
					this._Variations = value;
					this.SendPropertyChanged("Variations");
					this.OnVariationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageName", DbType="NVarChar(MAX)")]
		public string ImageName
		{
			get
			{
				return this._ImageName;
			}
			set
			{
				if ((this._ImageName != value))
				{
					this.OnImageNameChanging(value);
					this.SendPropertyChanging();
					this._ImageName = value;
					this.SendPropertyChanged("ImageName");
					this.OnImageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Watermark", DbType="NVarChar(MAX)")]
		public string Watermark
		{
			get
			{
				return this._Watermark;
			}
			set
			{
				if ((this._Watermark != value))
				{
					this.OnWatermarkChanging(value);
					this.SendPropertyChanging();
					this._Watermark = value;
					this.SendPropertyChanged("Watermark");
					this.OnWatermarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Border", DbType="NVarChar(MAX)")]
		public string Border
		{
			get
			{
				return this._Border;
			}
			set
			{
				if ((this._Border != value))
				{
					this.OnBorderChanging(value);
					this.SendPropertyChanging();
					this._Border = value;
					this.SendPropertyChanged("Border");
					this.OnBorderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Timeshifted", DbType="NChar(10)")]
		public string Timeshifted
		{
			get
			{
				return this._Timeshifted;
			}
			set
			{
				if ((this._Timeshifted != value))
				{
					this.OnTimeshiftedChanging(value);
					this.SendPropertyChanging();
					this._Timeshifted = value;
					this.SendPropertyChanged("Timeshifted");
					this.OnTimeshiftedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HandSizeModifier", DbType="Int")]
		public System.Nullable<int> HandSizeModifier
		{
			get
			{
				return this._HandSizeModifier;
			}
			set
			{
				if ((this._HandSizeModifier != value))
				{
					this.OnHandSizeModifierChanging(value);
					this.SendPropertyChanging();
					this._HandSizeModifier = value;
					this.SendPropertyChanged("HandSizeModifier");
					this.OnHandSizeModifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LifeModifier", DbType="Int")]
		public System.Nullable<int> LifeModifier
		{
			get
			{
				return this._LifeModifier;
			}
			set
			{
				if ((this._LifeModifier != value))
				{
					this.OnLifeModifierChanging(value);
					this.SendPropertyChanging();
					this._LifeModifier = value;
					this.SendPropertyChanged("LifeModifier");
					this.OnLifeModifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserved", DbType="NChar(10)")]
		public string Reserved
		{
			get
			{
				return this._Reserved;
			}
			set
			{
				if ((this._Reserved != value))
				{
					this.OnReservedChanging(value);
					this.SendPropertyChanging();
					this._Reserved = value;
					this.SendPropertyChanged("Reserved");
					this.OnReservedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReleaseDate", DbType="NVarChar(MAX)")]
		public string ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}
			set
			{
				if ((this._ReleaseDate != value))
				{
					this.OnReleaseDateChanging(value);
					this.SendPropertyChanging();
					this._ReleaseDate = value;
					this.SendPropertyChanged("ReleaseDate");
					this.OnReleaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rulings", DbType="NVarChar(MAX)")]
		public string Rulings
		{
			get
			{
				return this._Rulings;
			}
			set
			{
				if ((this._Rulings != value))
				{
					this.OnRulingsChanging(value);
					this.SendPropertyChanging();
					this._Rulings = value;
					this.SendPropertyChanged("Rulings");
					this.OnRulingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForeignNames", DbType="NVarChar(MAX)")]
		public string ForeignNames
		{
			get
			{
				return this._ForeignNames;
			}
			set
			{
				if ((this._ForeignNames != value))
				{
					this.OnForeignNamesChanging(value);
					this.SendPropertyChanging();
					this._ForeignNames = value;
					this.SendPropertyChanged("ForeignNames");
					this.OnForeignNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Printings", DbType="NVarChar(MAX)")]
		public string Printings
		{
			get
			{
				return this._Printings;
			}
			set
			{
				if ((this._Printings != value))
				{
					this.OnPrintingsChanging(value);
					this.SendPropertyChanging();
					this._Printings = value;
					this.SendPropertyChanged("Printings");
					this.OnPrintingsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalText", DbType="NVarChar(MAX)")]
		public string OriginalText
		{
			get
			{
				return this._OriginalText;
			}
			set
			{
				if ((this._OriginalText != value))
				{
					this.OnOriginalTextChanging(value);
					this.SendPropertyChanging();
					this._OriginalText = value;
					this.SendPropertyChanged("OriginalText");
					this.OnOriginalTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalType", DbType="NVarChar(MAX)")]
		public string OriginalType
		{
			get
			{
				return this._OriginalType;
			}
			set
			{
				if ((this._OriginalType != value))
				{
					this.OnOriginalTypeChanging(value);
					this.SendPropertyChanging();
					this._OriginalType = value;
					this.SendPropertyChanged("OriginalType");
					this.OnOriginalTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Legalities", DbType="NVarChar(MAX)")]
		public string Legalities
		{
			get
			{
				return this._Legalities;
			}
			set
			{
				if ((this._Legalities != value))
				{
					this.OnLegalitiesChanging(value);
					this.SendPropertyChanging();
					this._Legalities = value;
					this.SendPropertyChanged("Legalities");
					this.OnLegalitiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(MAX)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
